development:
  # <<: *default
  adapter: mysql2
  encoding: utf8
  database: db_development
  username: root
  host: localhost

test:
#   <<: *default
  adapter: mysql2
  database: db_test
  username: root
  host: localhost

production:
  # <<: *default
  adapter: mysql2
  database: db_production
  username: root
  host: localhost